# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Telegrafer.Telegrafer
PackageVersion: 0.0.2
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/Timo-Weike/Telegrafer/releases/download/v0.0.2/Telegrafer.WindowsInstaller.msi
  InstallerSha256: FD19223C884D43B462B0FE26ECB3EC7917D84E8BBF6D4770834453FCAEB32EE8
  ProductCode: '{6D15B77F-1DBE-4953-B76D-0906A5DF52D6}'
ManifestType: installer
ManifestVersion: 1.4.0
