name: Build and Package Avalonia App

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: ['6.x']

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET environment for building
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Install dependencies (e.g., restore NuGet packages)
      - name: Restore dependencies
        run: dotnet restore src/Telegrafer

      # Build the Avalonia application
      - name: Build the app
        run: dotnet build src/Telegrafer --configuration Release --no-restore

      # Publish the application for different OS platforms
      - name: Publish Avalonia App (Cross-platform)
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            dotnet publish src/Telegrafer -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -o ./publish/linux-x64
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            dotnet publish src/Telegrafer -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ./publish/win-x64
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            dotnet publish src/Telegrafer -c Release -r osx-x64 --self-contained -p:PublishSingleFile=true -o ./publish/osx-x64
          fi

      # Archive the build artifacts
      - name: Create artifact for ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./publish

  tag:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    outputs:
      new_tag: ${{ steps.add_tag.outputs.new_tag }}
    steps:
      - name: add_tag
        id: add_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          # Required for permission to tag the repo.
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          release_branches: release
          pre_release_branches: main
          append_to_pre_release_tag: prerelease

  # Optional: Create a release with the build artifacts
  release:
    runs-on: ubuntu-latest
    needs: tag
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads

      - name: zip
        run: |
          mkdir uploads
          zip uploads/Telegrafer-linux-x64.zip ./downloads/ubuntu-latest/linux-x64/* -r
          zip uploads/Telegrafer-osx-x64.zip ./downloads/macos-latest/osx-x64/* -r
          zip uploads/Telegrafer-win-x64.zip ./downloads/windows-latest/win-x64/* -r
      
      - name: 🛎️ Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.tag.outputs.new_tag }}
          artifacts: "uploads/**"
          prerelease: ${{ github.ref == 'refs/heads/release' && false || true }}
